// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// fast_traceC
double fast_traceC(const arma::mat& X, const arma::mat& Y);
RcppExport SEXP _RpESCA_fast_traceC(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_traceC(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// mat_vec_matC
arma::mat mat_vec_matC(const arma::mat& X, const arma::colvec& d, const arma::mat& Y);
RcppExport SEXP _RpESCA_mat_vec_matC(SEXP XSEXP, SEXP dSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(mat_vec_matC(X, d, Y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RpESCA_fast_traceC", (DL_FUNC) &_RpESCA_fast_traceC, 2},
    {"_RpESCA_mat_vec_matC", (DL_FUNC) &_RpESCA_mat_vec_matC, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_RpESCA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
