# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_traceC <- function(X, Y) {
    .Call('_RpESCA_fast_traceC', PACKAGE = 'RpESCA', X, Y)
}

mat_vec_matC <- function(X, d, Y) {
    .Call('_RpESCA_mat_vec_matC', PACKAGE = 'RpESCA', X, d, Y)
}

